DELETE FROM forum_comments;
DELETE FROM forum_threads;
DELETE FROM rehearsal_logs;
DELETE FROM score_instruments;
DELETE FROM scores;
DELETE FROM instruments;
DELETE FROM organization_members;
DELETE FROM organizations;
DELETE FROM users;

INSERT INTO instruments (id, name, family, transposition, is_transposing, range, concert_range, clef, dynamic_range, techniques, historical_info, maintenance_tips)
VALUES
  ('violin', 'Violín', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"G3","highest_note":"E7"}', '{"lowest_note":"G3","highest_note":"E7"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","pizzicato","spiccato","col legno","sul ponticello"]', 'Instrumento rey de la sección de cuerdas.', 'Limpiar la resina de las cuerdas después de tocar.'),
  ('violonchelo', 'Violonchelo', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"C2","highest_note":"G5"}', '{"lowest_note":"C2","highest_note":"G5"}', '["bass","tenor","treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","pizzicato","spiccato","sul tasto"]', 'Cuerda grave con registro amplio y timbre cálido.', 'Revisar la pica y limpiar la madera con paño seco.'),
  ('flauta', 'Flauta traversa', 'winds', 'En Do (no transpone)', FALSE, '{"lowest_note":"C4","highest_note":"D7"}', '{"lowest_note":"C4","highest_note":"D7"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","frullato","doble picado","armónicos"]', 'Viento madera de agilidad y brillo melódico.', 'Secar el interior con varilla y gasa tras cada sesión.'),
  ('trompa', 'Trompa (Corno)', 'brass', 'En Fa (suena 5ª justa abajo)', TRUE, '{"lowest_note":"F2","highest_note":"C6"}', '{"lowest_note":"Bb1","highest_note":"F5"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","sordina","cuivré","bouché"]', 'Instrumento noble de metal con campana trasera.', 'Drenar el agua de los tubos y aceitar rotores.'),
  ('timbales', 'Timbales', 'percussion', 'Afinación determinada', FALSE, '{"lowest_note":"F2","highest_note":"C4"}', '{"lowest_note":"F2","highest_note":"C4"}', '["bass"]', '["pp","p","mp","mf","f","ff"]', '["redoble","glissando","golpe simple","apagar parche"]', 'Percusión orquestal afinable por pedal.', 'Mantener parches protegidos del polvo y cambios de clima.'),
  ('arpa', 'Arpa', 'keyboard', 'En Do (con pedales)', FALSE, '{"lowest_note":"C2","highest_note":"G7"}', '{"lowest_note":"C2","highest_note":"G7"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["glissando","arpegio","bisbigliando","armónicos","près de la table"]', 'Instrumento de 47 cuerdas y 7 pedales.', 'Afinar periódicamente y evitar cambios bruscos de temperatura.'),
  ('trumpet', 'Trompeta', 'brass', 'En Sib (suena 2ª mayor abajo)', TRUE, '{"lowest_note":"F#3","highest_note":"C6"}', '{"lowest_note":"E3","highest_note":"Bb5"}', '["treble"]', '["p","mp","mf","f","ff"]', '["legato","staccato","doble picado","triple picado","sordina straight","sordina harmon"]', 'Metal brillante, versátil en clásico y jazz.', 'Lubricar pistones y limpiar bombas regularmente.'),
  ('flute', 'Flauta', 'winds', 'En Do (no transpone)', FALSE, '{"lowest_note":"C4","highest_note":"C7"}', '{"lowest_note":"C4","highest_note":"C7"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","frullato","doble picado"]', 'Instrumento de viento madera soprano.', 'Limpiar la saliva interior después de tocar.'),
  ('piano', 'Piano', 'keyboard', 'En Do (no transpone)', FALSE, '{"lowest_note":"A0","highest_note":"C8"}', '{"lowest_note":"A0","highest_note":"C8"}', '["treble","bass"]', '["ppp","pp","p","mp","mf","f","ff","fff"]', '["legato","staccato","pedal de resonancia","una corda"]', 'Instrumento polifónico de teclado de 88 teclas.', 'Afinar 1 o 2 veces al año y mantener teclado cubierto.'),
  ('guitar', 'Guitarra', 'strings', 'En Do (suena 8ª abajo)', TRUE, '{"lowest_note":"E2","highest_note":"E5"}', '{"lowest_note":"E2","highest_note":"E5"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["punteo","rasgueo","arpegio","ligados","cejilla"]', 'Instrumento de cuerdas pulsadas de 6 cuerdas.', 'Cambiar cuerdas gastadas y guardar en estuche.'),
  ('cello', 'Cello', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"C2","highest_note":"G5"}', '{"lowest_note":"C2","highest_note":"G5"}', '["bass","tenor","treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","pizzicato","spiccato"]', 'Nombre alternativo del violonchelo.', 'Limpiar resina y cuidar la humedad ambiente.'),
  ('violin_vio', 'Violín Eléctrico', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"G3","highest_note":"E7"}', '{"lowest_note":"G3","highest_note":"E7"}', '["treble"]', '["p","mp","mf","f","ff"]', '["pizzicato","arco","efectos electrónicos"]', 'Violín amplificado electrónicamente.', 'Cuidar las pastillas piezoeléctricas y conexiones jack.'),
  ('clarinet', 'Clarinete', 'winds', 'En Sib (suena 2ª mayor abajo)', TRUE, '{"lowest_note":"E3","highest_note":"A6"}', '{"lowest_note":"D3","highest_note":"G6"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","glissando"]', 'Instrumento de viento madera con caña simple.', 'Guardar cañas secas y engrasar corchos periódicamente.'),
  ('saxophone', 'Saxofón Alto', 'winds', 'En Mib (suena 6ª mayor abajo)', TRUE, '{"lowest_note":"Bb3","highest_note":"F#6"}', '{"lowest_note":"Db3","highest_note":"A5"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["subtone","growl","glissando","vibrato"]', 'Viento con cuerpo de metal y boquilla de caña.', 'Limpiar zapatillas y tudel con escobillón tras su uso.'),
  ('drums', 'Batería', 'percussion', 'Sin afinación fija', FALSE, '{"lowest_note":"C1","highest_note":"C5"}', '{"lowest_note":"C1","highest_note":"C5"}', '["percussion"]', '["pp","p","mp","mf","f","ff"]', '["rimshot","redoble","ghost notes"]', 'Set de tambores y platillos para percusión rítmica.', 'Ajustar tensión de parches y engrasar herrajes.'),
  ('oboe', 'Oboe', 'winds', 'En Do (no transpone)', FALSE, '{"lowest_note":"Bb3","highest_note":"G6"}', '{"lowest_note":"Bb3","highest_note":"G6"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato"]', 'Viento madera con caña doble y timbre penetrante.', 'Secar cuerpo de madera cuidadosamente para evitar grietas.'),
  ('bassoon', 'Fagot', 'winds', 'En Do (no transpone)', FALSE, '{"lowest_note":"Bb1","highest_note":"Eb5"}', '{"lowest_note":"Bb1","highest_note":"Eb5"}', '["bass","tenor"]', '["pp","p","mp","mf","f","ff"]', '["staccato","legato","vibrato"]', 'Bajo de la familia de viento madera con caña doble.', 'Limpiar tudel y vaciar humedad de la bota inferior.'),
  ('french_horn', 'Corno Francés', 'brass', 'En Fa (suena 5ª justa abajo)', TRUE, '{"lowest_note":"F2","highest_note":"C6"}', '{"lowest_note":"Bb1","highest_note":"F5"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","bouché","sordina"]', 'Trompa con boquilla cónica y campana.', 'Aceitar cilindros y vaciar llaves de desagüe.'),
  ('tuba', 'Tuba', 'brass', 'En Do / Sib', FALSE, '{"lowest_note":"D1","highest_note":"F4"}', '{"lowest_note":"D1","highest_note":"F4"}', '["bass"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato"]', 'El instrumento más grave de la familia de viento metal.', 'Lavado interno periódico y lubricación de bombas pesadas.'),
  ('timpani', 'Timbales Sinfónicos', 'percussion', 'Afinación determinada', FALSE, '{"lowest_note":"D2","highest_note":"A3"}', '{"lowest_note":"D2","highest_note":"A3"}', '["bass"]', '["pp","p","mp","mf","f","ff"]', '["redoble","glissando"]', 'Juego orquestal de calderos de cobre.', 'Calibrar pedales mecánicos y lubricar mecanismos.'),
  ('marimba', 'Marimba', 'percussion', 'En Do (no transpone)', FALSE, '{"lowest_note":"C2","highest_note":"C7"}', '{"lowest_note":"C2","highest_note":"C7"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["trémolo de 4 baquetas","glissando"]', 'Láminas de madera afinadas con tubos resonadores.', 'Cuidar láminas de golpes fuertes y no exponer al sol directo.'),
  ('vibraphone', 'Vibráfono', 'percussion', 'En Do (no transpone)', FALSE, '{"lowest_note":"F3","highest_note":"F6"}', '{"lowest_note":"F3","highest_note":"F6"}', '["treble"]', '["pp","p","mp","mf","f","ff"]', '["pedal damper","motor vibrato","dead stroke"]', 'Láminas de metal con motor para efecto trémolo.', 'Revisar motor de aspas y mecanismo de pedal sordina.'),
  ('ukulele', 'Ukelele', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"C4","highest_note":"A5"}', '{"lowest_note":"C4","highest_note":"A5"}', '["treble"]', '["p","mp","mf","f"]', '["rasgueo","arpegio"]', 'Instrumento de 4 cuerdas de origen hawaiano.', 'Mantener afinado en G4-C4-E4-A4 y proteger clavijas.'),
  ('banjo', 'Banjo', 'strings', 'En Do / Sol', FALSE, '{"lowest_note":"D3","highest_note":"D6"}', '{"lowest_note":"D3","highest_note":"D6"}', '["treble"]', '["p","mp","mf","f","ff"]', '["clawhammer","scruggs style"]', 'Instrumento folclórico de cuerda con parche tipo tambor.', 'Ajustar la tensión del parche circular según se requiera.'),
  ('mandolin', 'Mandolina', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"G3","highest_note":"E7"}', '{"lowest_note":"G3","highest_note":"E7"}', '["treble"]', '["p","mp","mf","f","ff"]', '["trémolo de púa","chop chord"]', 'Instrumento de cuerdas dobles afinado igual al violín.', 'Cuidar el puente flotante y lubricar clavijero.'),
  ('viola', 'Viola', 'strings', 'En Do (no transpone)', FALSE, '{"lowest_note":"C3","highest_note":"A6"}', '{"lowest_note":"C3","highest_note":"A6"}', '["alto","treble"]', '["pp","p","mp","mf","f","ff"]', '["legato","staccato","pizzicato"]', 'Voz intermedia de las cuerdas, afinada en quintas.', 'Limpiar resina y usar almohadilla adecuada.'),
  ('trombone', 'Trombón', 'brass', 'En Do (no transpone)', FALSE, '{"lowest_note":"E2","highest_note":"F5"}', '{"lowest_note":"E2","highest_note":"F5"}', '["bass","tenor"]', '["pp","p","mp","mf","f","ff"]', '["glissando de vara","legato","staccato"]', 'Instrumento de viento metal con vara deslizante.', 'Aplicar crema/lubricante a la vara interna tras secar.'),
  ('xylophone', 'Xilófono', 'percussion', 'En Do (suena 8ª arriba)', TRUE, '{"lowest_note":"F4","highest_note":"C8"}', '{"lowest_note":"F3","highest_note":"C7"}', '["treble"]', '["p","mp","mf","f","ff"]', '["redoble","golpe simple"]', 'Láminas de madera dura con sonido brillante y seco.', 'Usar baquetas del material adecuado para no marcar maderas.'),
  ('glockenspiel', 'Glockenspiel (Liras/Campanillas)', 'percussion', 'En Do (suena 2 8vas arriba)', TRUE, '{"lowest_note":"G5","highest_note":"C8"}', '{"lowest_note":"G3","highest_note":"C6"}', '["treble"]', '["p","mp","mf","f"]', '["golpe seco"]', 'Pequeñas placas de acero afinadas.', 'Limpiar placas metálicas de huellas y grasa.'),
  ('chimes', 'Campanas Tubulares', 'percussion', 'En Do (no transpone)', FALSE, '{"lowest_note":"C4","highest_note":"F5"}', '{"lowest_note":"C4","highest_note":"F5"}', '["treble"]', '["p","mp","mf","f","ff"]', '["pedal damper"]', 'Tubos de bronce suspendidos afinados por longitud.', 'Usar mazas de cuero/madera especial para campanas.'),
  ('synthesizer', 'Sintetizador', 'keyboard', 'En Do (rango variable)', FALSE, '{"lowest_note":"C0","highest_note":"C9"}', '{"lowest_note":"C0","highest_note":"C9"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["arpegiador","modulación","pitch bend"]', 'Generador electrónico y modulador de formas de onda.', 'Mantener libre de polvo en potenciómetros y faders.'),
  ('electronic', 'Instrumento Electrónico', 'keyboard', 'En Do', FALSE, '{"lowest_note":"C0","highest_note":"C9"}', '{"lowest_note":"C0","highest_note":"C9"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["control midi","samplers"]', 'Controladores MIDI y módulos sonoros digitales.', 'Desconectar alimentación en tormentas eléctricas.'),
  ('theremin', 'Theremín', 'electronic', 'Continuo (sin notas fijas)', FALSE, '{"lowest_note":"C1","highest_note":"C7"}', '{"lowest_note":"C1","highest_note":"C7"}', '["treble"]', '["pp","p","mp","mf","f"]', '["vibrato manual","glissando continuo"]', 'Instrumento controlado sin contacto físico mediante antenas.', 'Calibrar antenas según la proximidad del entorno.'),
  ('bagpipes', 'Gaita', 'winds', 'En Sib / Do', FALSE, '{"lowest_note":"G4","highest_note":"A5"}', '{"lowest_note":"G4","highest_note":"A5"}', '["treble"]', '["f","ff"]', '["grace notes","bordón continuo"]', 'Instrumento de lengüeta con fuelle y bordones.', 'Hidratar el cuero de la bolsa y ajustar cañas con cuidado.'),
  ('accordion', 'Acordeón', 'keyboard', 'En Do (no transpone)', FALSE, '{"lowest_note":"F2","highest_note":"A6"}', '{"lowest_note":"F2","highest_note":"A6"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["bellows shake","cambio de registros"]', 'Lengüetas libres accionadas por fuelle manual.', 'Guardar verticalmente y proteger fuelles de dobleces bruscos.'),
  ('concertina', 'Concertina', 'keyboard', 'En Do / Sol', FALSE, '{"lowest_note":"G3","highest_note":"C7"}', '{"lowest_note":"G3","highest_note":"C7"}', '["treble"]', '["p","mp","mf","f"]', '["articulación rápida"]', 'Instrumento hexagonal portátil de lengüetas y fuelle.', 'Evitar humedad que oxide las lengüetas internas.'),
  ('harmonica', 'Armónica', 'winds', 'Diatónica / Cromática', FALSE, '{"lowest_note":"C4","highest_note":"C7"}', '{"lowest_note":"C4","highest_note":"C7"}', '["treble"]', '["p","mp","mf","f"]', '["bending","overblow","vibrato manual"]', 'Pequeño instrumento de viento soplado y aspirado.', 'Tocar con la boca limpia y sacudir restos de saliva.'),
  ('recorder', 'Flauta Dulce', 'winds', 'En Do / Fa', FALSE, '{"lowest_note":"C4","highest_note":"D6"}', '{"lowest_note":"C4","highest_note":"D6"}', '["treble"]', '["p","mp","mf","f"]', '["articulación doble","digitación barroca"]', 'Flauta de pico vertical común en música barroca y escolar.', 'Secar el bloque con cuidado y no frotar el bisel.'),
  ('zither', 'Cítara', 'strings', 'En Do', FALSE, '{"lowest_note":"C2","highest_note":"C6"}', '{"lowest_note":"C2","highest_note":"C6"}', '["treble","bass"]', '["p","mp","mf"]', '["punteo con anillo"]', 'Cuerdas extendidas sobre caja armónica sin mástil.', 'Afinar clavijas con llave adecuada.'),
  ('lyre', 'Lira', 'strings', 'En Do', FALSE, '{"lowest_note":"C4","highest_note":"C6"}', '{"lowest_note":"C4","highest_note":"C6"}', '["treble"]', '["p","mp","mf"]', '["pulsación con púa de hueso"]', 'Instrumento de cuerda pulsada de la antigüedad clásica.', 'Mantener tensión equilibrada en el marco de madera.'),
  ('kora', 'Kora', 'strings', 'En Fa / Do', FALSE, '{"lowest_note":"F2","highest_note":"F5"}', '{"lowest_note":"F2","highest_note":"F5"}', '["treble","bass"]', '["p","mp","mf","f"]', '["polirritmia con pulgares e índices"]', 'Arpa-laúd africana de 21 cuerdas construida con calabaza.', 'Cuidar el cuero de la caja y las anillas de afinación.'),
  ('erhu', 'Erhu', 'strings', 'En Re (no transpone)', FALSE, '{"lowest_note":"D4","highest_note":"G6"}', '{"lowest_note":"D4","highest_note":"G6"}', '["treble"]', '["p","mp","mf","f"]', '["portamento","vibrato rápido"]', 'Violín chino de 2 cuerdas con arco atrapado entre ellas.', 'Cuidar la piel de serpiente de la humedad y destensar arco.'),
  ('pipa', 'Pipa', 'strings', 'En Do', FALSE, '{"lowest_note":"A2","highest_note":"D6"}', '{"lowest_note":"A2","highest_note":"D6"}', '["treble"]', '["p","mp","mf","f","ff"]', '["lunzhi (trémolo de 5 dedos)","tan-tiao"]', 'Laúd tradicional chino de 4 cuerdas y forma de pera.', 'Cuidar trastes y usar protectores de uñas adecuados.'),
  ('guzheng', 'Guzheng', 'strings', 'Escala pentatónica', FALSE, '{"lowest_note":"D2","highest_note":"D6"}', '{"lowest_note":"D2","highest_note":"D6"}', '["treble","bass"]', '["pp","p","mp","mf","f","ff"]', '["glissando con uñas postizas","flexión de cuerda"]', 'Cítara tradicional china con 21 cuerdas y puentes móviles.', 'Ajustar posición de los puentes móviles con suavidad.'),
  ('koto', 'Koto', 'strings', 'Escala pentatónica', FALSE, '{"lowest_note":"D3","highest_note":"A5"}', '{"lowest_note":"D3","highest_note":"A5"}', '["treble"]', '["p","mp","mf","f"]', '["hiku","oshide (presión tras el puente)"]', 'Cítara tradicional japonesa de 13 cuerdas de seda/nylon.', 'Destensar y cubrir cuando no esté en uso constante.');

INSERT INTO scores (id, title, composer, arranger, owner_id, organization_id, file_url, file_format, file_size, duration_seconds)
VALUES
  ('1', 'Sinfonía n.º 5', 'L. van Beethoven', NULL, NULL, NULL, 'https://example.com/scores/1.pdf', 'pdf', 1240000, 480),
  ('2', 'Danzón n.º 2', 'Arturo Márquez', NULL, NULL, NULL, 'https://example.com/scores/2.pdf', 'pdf', 800000, 540),
  ('3', 'Las cuatro estaciones', 'A. Vivaldi', NULL, NULL, NULL, 'https://example.com/scores/3.musicxml', 'musicxml', 450000, 600),
  ('4', 'El amor brujo', 'M. de Falla', NULL, NULL, NULL, 'https://example.com/scores/4.pdf', 'pdf', 1100000, 510),
  ('5', 'Clair de Lune', 'C. Debussy', NULL, NULL, NULL, 'https://example.com/scores/5.pdf', 'pdf', 420000, 300),
  ('6', 'Suite Holberg', 'E. Grieg', NULL, NULL, NULL, 'https://example.com/scores/6.pdf', 'pdf', 690000, 420);

INSERT INTO rehearsal_logs (id, title, type, date_text, time_text, venue, attendees_count, notes)
VALUES
  ('1', 'Ensayo general', 'General', 'Jueves, 31 de julio', '19:00-22:00', 'Auditorio Manuel de Falla', 46, 'Revisar tutti en compás 45'),
  ('2', 'Seccionales de cuerdas', 'Seccional', 'Lunes, 28 de julio', '18:00-20:00', 'Sala de Ensayo B', 18, 'Trabajar articulación staccato'),
  ('3', 'Concierto de cámara', 'Concierto', 'Sábado, 02 de agosto', '20:30-22:30', 'Sala Principal', 52, 'Código de vestimenta: gala');

INSERT INTO forum_threads (id, title, author, meta, category, likes)
VALUES
  ('1', 'Recomendaciones para programar música latinoamericana', 'Valentina Ruiz', 'Hace 2 h', 'Repertorio', 15),
  ('2', '¿Cómo trabajan las dinámicas en seccionales?', 'Martín López', 'Ayer', 'Técnica', 8),
  ('3', 'Recursos para preparar una audición de violín', 'Elena Torres', 'Hace 2 días', 'Recursos', 24);

INSERT INTO forum_comments (id, thread_id, author, date_text, content)
VALUES
  ('c1', '1', 'Martín López', 'Hace 1 h', 'Recomiendo incluir piezas de Arturo Márquez y Silvestre Revueltas.'),
  ('c2', '1', 'Elena Torres', 'Hace 30 min', 'También los arreglos de Piazzolla para cuerdas funcionan excelentemente.'),
  ('c3', '2', 'Carlos Mendonça', 'Ayer', 'Usamos afinadores con espectrómetro y metrónomo subdividido.');